---

- name: Check whether config.php contains a dbdriveroptions block
  become: true
  become_user: www-data
  ansible.builtin.lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: "dbdriveroptions"
    state: absent
  check_mode: true  # The file will never actually be modified
  register: dbdriveroptions
  changed_when: not dbdriveroptions.found

- name: Ensure config.php contains a dbdriveroptions block
  become: true
  become_user: www-data
  ansible.builtin.lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    line: "  'dbdriveroptions' => array ( ),"
    insertbefore: '^\s*\);\s*$'
  when: not dbdriveroptions.found

- name: Setup empty dbdriveroptions configuration in config.php
  become: true
  become_user: www-data
  ansible.builtin.replace:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: '''dbdriveroptions''(\s|\n)*=>(\s|\n)*array(\s|\n)*\((.|\n)*?\)(\s|\n)*,\s*\n'
    replace: |
      'dbdriveroptions' => array ( ),
  when: nextcloud_mysql_client_cert == ''

- name: Ensure directory /etc/mysql/certs exists
  ansible.builtin.file:
    dest: /etc/mysql/certs
    state: directory
    mode: "0755"
  when: nextcloud_mysql_client_cert != ''

- name: Install MySQL client key
  ansible.builtin.copy:
    src: "{{ nextcloud_mysql_client_key }}"
    dest: /etc/mysql/certs/client-key.pem
    group: www-data
    mode: "0640"
  when: nextcloud_mysql_client_cert != ''

- name: Install MySQL client cert
  ansible.builtin.copy:
    src: "{{ nextcloud_mysql_client_cert }}"
    dest: /etc/mysql/certs/client-cert.pem
    group: www-data
    mode: "0644"
  when: nextcloud_mysql_client_cert != ''

- name: Install MySQL ca cert
  ansible.builtin.copy:
    src: "{{ nextcloud_mysql_ca_cert }}"
    dest: /etc/mysql/certs/ca.pem
    group: www-data
    mode: "0644"
  when: nextcloud_mysql_client_cert != ''

- name: Setup dbdriveroptions configuration in config.php
  become: true
  become_user: www-data
  ansible.builtin.replace:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: '''dbdriveroptions''(\s|\n)*=>(\s|\n)*array(\s|\n)*\((.|\n)*?\)(\s|\n)*,\s*\n'
    replace: |
      'dbdriveroptions' =>
        array (
          \\PDO::MYSQL_ATTR_SSL_KEY => "/etc/mysql/certs/client-key.pem",
          \\PDO::MYSQL_ATTR_SSL_CERT => "/etc/mysql/certs/client-cert.pem",
          \\PDO::MYSQL_ATTR_SSL_CA => "/etc/mysql/certs/ca.pem",
          \\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
        ),
  when: nextcloud_mysql_client_cert != ''
