---
- name: Restart redis
  ansible.builtin.service:
    name: redis
    state: restarted

- name: Activate richdocuments config
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/{{ nextcloud_fqdn }}/nextcloud
    cmd: php occ richdocuments:activate-config
  changed_when: true

- name: Update htaccess
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/{{ nextcloud_fqdn }}/nextcloud
    cmd: php occ maintenance:update:htaccess
  changed_when: true

- name: Restart php-fpm
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    state: restarted
